name: Deploy automation-gui-example

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ master ]
permissions:
  contents: read

jobs:
  # deploy the Static Web App code including a Managed Function when enabled
  swa-build-and-deploy:
    permissions:
      contents: read
      pull-requests: write
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: SWA Build and Deploy
    steps:
      # deploy a Managed Function with this job when the AZURE_FUNCTIONAPP_NAME repo variable is not set
      - name: Set Managed Function api_location
        if: ${{ !vars.AZURE_FUNCTIONAPP_NAME }}
        run: echo "API_LOCATION=api" >> $GITHUB_ENV
      # deploy a "Bring your own" Function in a separate job, this job will skip any Function deployment
      - name: Set BYO Function api_location
        if: vars.AZURE_FUNCTIONAPP_NAME
        run: echo "API_LOCATION=" >> $GITHUB_ENV
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: .
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ./dist

  # deploy a Function App for the API when the "Bring your own" Function option is configured
  api-build-and-deploy:
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    # if AZURE_FUNCTIONAPP_NAME has been set we are deploying Function App
    if: vars.AZURE_FUNCTIONAPP_NAME && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed'))
    runs-on: ubuntu-latest
    name: API Build and Deploy
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Resolve Python dependencies
        shell: bash
        run: |
          pushd './api'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd
      - name: Authenticate with Azure tenant
        uses: Azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - name: Run the Azure Functions action
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
          package: ./api

  close-pull-request:
    permissions:
      contents: none
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: close
